
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Jun  6 2024 17:33:03 CDT (Jun  6 2024 22:33:03 UTC)

// Verification Directory fv/mac 

module mac(IN, W, clk, rstb, OUT);
  input [3:0] IN, W;
  input clk, rstb;
  output [11:0] OUT;
  wire [3:0] IN, W;
  wire clk, rstb;
  wire [11:0] OUT;
  wire [11:0] B;
  wire [11:0] A;
  wire [3:0] cycle_count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, n_0, n_1;
  wire n_2, n_3, n_5, n_6, n_7, n_8, n_9, n_12;
  wire n_13, n_15, n_16, n_17, n_18, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_48, n_50;
  wire n_51, n_52, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_165;
  wire n_166, n_167, n_168, n_169, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_214, n_215;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_234;
  wire n_274, n_279, n_320, n_397, n_669, n_672, n_673, n_674;
  wire n_675, n_676, n_781;
  DFFR_X1 \OUT_reg[11] (.RN (rstb), .CK (clk), .D (n_223), .Q
       (OUT[11]), .QN (UNCONNECTED));
  XNOR2_X1 g5136__8780(.A (n_221), .B (n_17), .ZN (n_223));
  DFFR_X1 \OUT_reg[10] (.RN (rstb), .CK (clk), .D (n_222), .Q
       (OUT[10]), .QN (UNCONNECTED0));
  FA_X1 g5141__4296(.A (B[10]), .B (A[10]), .CI (n_219), .CO (n_221),
       .S (n_222));
  DFFR_X1 \OUT_reg[9] (.RN (rstb), .CK (clk), .D (n_220), .Q (OUT[9]),
       .QN (UNCONNECTED1));
  FA_X1 g5150__3772(.A (B[9]), .B (A[9]), .CI (n_217), .CO (n_219), .S
       (n_220));
  DFFR_X1 \OUT_reg[8] (.RN (rstb), .CK (clk), .D (n_218), .Q (OUT[8]),
       .QN (UNCONNECTED2));
  DFFR_X1 \B_reg[10] (.RN (rstb), .CK (clk), .D (n_674), .Q (B[10]),
       .QN (n_70));
  FA_X1 g5156__1474(.A (B[8]), .B (A[8]), .CI (n_209), .CO (n_217), .S
       (n_218));
  DFFR_X1 \B_reg[11] (.RN (rstb), .CK (clk), .D (n_215), .Q (B[11]),
       .QN (UNCONNECTED3));
  XNOR2_X1 g5139__9682(.A (n_207), .B (n_58), .ZN (n_215));
  OAI21_X1 g5135__2683(.A (n_134), .B1 (n_212), .B2 (n_133), .ZN
       (n_214));
  DFFR_X1 \B_reg[9] (.RN (rstb), .CK (clk), .D (n_211), .Q (B[9]), .QN
       (UNCONNECTED4));
  DFFR_X1 \OUT_reg[7] (.RN (rstb), .CK (clk), .D (n_210), .Q (OUT[7]),
       .QN (UNCONNECTED5));
  XNOR2_X1 g5140__6877(.A (n_208), .B (n_123), .ZN (n_211));
  FA_X1 g5161__2900(.A (B[7]), .B (A[7]), .CI (n_202), .CO (n_209), .S
       (n_210));
  NOR2_X1 g5143__2391(.A1 (n_208), .A2 (n_126), .ZN (n_212));
  OAI211_X1 g5146__7675(.A (n_204), .B (n_106), .C1 (n_115), .C2
       (n_125), .ZN (n_207));
  DFFR_X1 \B_reg[8] (.RN (rstb), .CK (clk), .D (n_206), .Q (B[8]), .QN
       (n_0));
  AOI21_X1 g5144__7118(.A (n_114), .B1 (n_205), .B2 (n_96), .ZN
       (n_208));
  XNOR2_X1 g5145__8757(.A (n_205), .B (n_110), .ZN (n_206));
  NAND2_X1 g5149__1786(.A1 (n_205), .A2 (n_127), .ZN (n_204));
  DFFR_X1 \B_reg[7] (.RN (rstb), .CK (clk), .D (n_201), .Q (B[7]), .QN
       (UNCONNECTED6));
  DFFR_X1 \OUT_reg[6] (.RN (rstb), .CK (clk), .D (n_203), .Q (OUT[6]),
       .QN (UNCONNECTED7));
  NAND2_X2 g5151__5953(.A1 (n_200), .A2 (n_151), .ZN (n_205));
  FA_X1 g5166__5703(.A (B[6]), .B (A[6]), .CI (n_195), .CO (n_202), .S
       (n_203));
  XNOR2_X1 g5152__7114(.A (n_199), .B (n_152), .ZN (n_201));
  NAND2_X1 g5154__5266(.A1 (n_199), .A2 (n_150), .ZN (n_200));
  DFFR_X1 \B_reg[6] (.RN (rstb), .CK (clk), .D (n_198), .Q (B[6]), .QN
       (n_20));
  OAI21_X1 g5157__2250(.A (n_673), .B1 (n_197), .B2 (n_180), .ZN
       (n_199));
  XNOR2_X1 g5158__6083(.A (n_181), .B (n_197), .ZN (n_198));
  DFFR_X1 \B_reg[5] (.RN (rstb), .CK (clk), .D (n_194), .Q (B[5]), .QN
       (UNCONNECTED8));
  DFFR_X1 \OUT_reg[5] (.RN (rstb), .CK (clk), .D (n_196), .Q (OUT[5]),
       .QN (UNCONNECTED9));
  FA_X1 g5172__2703(.A (B[5]), .B (A[5]), .CI (n_188), .CO (n_195), .S
       (n_196));
  AOI21_X2 g5162__5795(.A (n_183), .B1 (n_193), .B2 (n_186), .ZN
       (n_197));
  XNOR2_X1 g5163__7344(.A (n_187), .B (n_193), .ZN (n_194));
  DFFR_X1 \B_reg[4] (.RN (rstb), .CK (clk), .D (n_192), .Q (B[4]), .QN
       (n_120));
  NAND2_X2 g5167__1840(.A1 (n_191), .A2 (n_179), .ZN (n_193));
  XOR2_X1 g5168__5019(.A (n_178), .B (n_190), .Z (n_192));
  DFFR_X1 \OUT_reg[4] (.RN (rstb), .CK (clk), .D (n_189), .Q (OUT[4]),
       .QN (UNCONNECTED10));
  NAND2_X1 g5171__1857(.A1 (n_190), .A2 (n_172), .ZN (n_191));
  DFFR_X1 \B_reg[3] (.RN (rstb), .CK (clk), .D (n_185), .Q (n_95), .QN
       (B[3]));
  FA_X1 g5181__9906(.A (B[4]), .B (A[4]), .CI (n_168), .CO (n_188), .S
       (n_189));
  NAND2_X1 g5178__8780(.A1 (n_186), .A2 (n_182), .ZN (n_187));
  OAI21_X2 g5173__4296(.A (n_147), .B1 (n_184), .B2 (n_149), .ZN
       (n_190));
  XNOR2_X1 g5174__3772(.A (n_781), .B (n_184), .ZN (n_185));
  INV_X1 g5185(.A (n_182), .ZN (n_183));
  NAND2_X1 g5187__1474(.A1 (n_162), .A2 (n_176), .ZN (n_186));
  NOR2_X1 g5177__4547(.A1 (n_180), .A2 (n_171), .ZN (n_181));
  INV_X1 g5179(.A (n_177), .ZN (n_179));
  DFFR_X1 \B_reg[2] (.RN (rstb), .CK (clk), .D (n_174), .Q (n_29), .QN
       (B[2]));
  HA_X1 g5182__9682(.A (n_166), .B (n_154), .CO (n_177), .S (n_178));
  NAND2_X1 g5186__2683(.A1 (n_161), .A2 (n_175), .ZN (n_182));
  INV_X1 g5188(.A (n_175), .ZN (n_176));
  XOR2_X1 g5192__1309(.A (n_173), .B (n_160), .Z (n_174));
  AOI21_X2 g5190__6877(.A (n_159), .B1 (n_173), .B2 (n_144), .ZN
       (n_184));
  NAND2_X1 g5195__2900(.A1 (n_167), .A2 (n_155), .ZN (n_172));
  INV_X1 g5180(.A (n_673), .ZN (n_171));
  DFFR_X1 \OUT_reg[3] (.RN (rstb), .CK (clk), .D (n_169), .Q (OUT[3]),
       .QN (UNCONNECTED11));
  DFFR_X1 \B_reg[1] (.RN (rstb), .CK (clk), .D (n_165), .Q (n_72), .QN
       (B[1]));
  OAI21_X1 g5189__7675(.A (n_90), .B1 (n_158), .B2 (n_156), .ZN
       (n_175));
  FA_X1 g5197__7118(.A (n_95), .B (A[3]), .CI (n_234), .CO (n_168), .S
       (n_169));
  AND2_X1 g5184__8757(.A1 (n_140), .A2 (n_163), .ZN (n_180));
  INV_X1 g5202(.A (n_166), .ZN (n_167));
  FA_X1 g5198__1786(.A (n_122), .B (n_111), .CI (n_3), .CO (n_173), .S
       (n_165));
  INV_X1 g5201(.A (n_161), .ZN (n_162));
  XNOR2_X1 g5204__5953(.A (n_157), .B (n_145), .ZN (n_166));
  HA_X1 g5205__5703(.A (n_143), .B (n_142), .CO (n_159), .S (n_160));
  AOI21_X1 g5200__7114(.A (n_129), .B1 (n_157), .B2 (n_130), .ZN
       (n_158));
  MUX2_X1 g5193__5266(.A (n_138), .B (n_71), .S (n_156), .Z (n_163));
  INV_X1 g5207(.A (n_154), .ZN (n_155));
  XNOR2_X1 g5203__6083(.A (n_139), .B (n_137), .ZN (n_161));
  OAI21_X1 g5209__2703(.A (n_116), .B1 (n_124), .B2 (n_156), .ZN
       (n_154));
  DFFR_X1 \cycle_count_reg[3] (.RN (rstb), .CK (clk), .D (n_132), .Q
       (UNCONNECTED12), .QN (cycle_count[3]));
  NAND2_X1 g5206__5795(.A1 (n_151), .A2 (n_150), .ZN (n_152));
  NOR2_X1 g5215__7344(.A1 (n_146), .A2 (n_148), .ZN (n_149));
  NAND2_X1 g5216__1840(.A1 (n_146), .A2 (n_148), .ZN (n_147));
  NAND2_X1 g5217__5019(.A1 (n_121), .A2 (n_128), .ZN (n_145));
  OR2_X2 g5219__1857(.A1 (n_143), .A2 (n_142), .ZN (n_144));
  NAND3_X1 g5214__9906(.A1 (n_107), .A2 (n_136), .A3 (n_100), .ZN
       (n_139));
  AOI21_X1 g5199__8780(.A (n_108), .B1 (n_137), .B2 (n_136), .ZN
       (n_138));
  OR2_X1 g5265__4296(.A1 (n_134), .A2 (n_133), .ZN (n_135));
  NOR2_X1 g5218__3772(.A1 (n_105), .A2 (n_156), .ZN (n_132));
  DFFR_X1 \OUT_reg[2] (.RN (rstb), .CK (clk), .D (n_104), .Q (OUT[2]),
       .QN (UNCONNECTED13));
  NAND2_X1 g5233__1474(.A1 (n_97), .A2 (n_120), .ZN (n_130));
  INV_X1 g5229(.A (n_128), .ZN (n_129));
  NOR3_X1 g5250__4547(.A1 (n_109), .A2 (n_126), .A3 (n_125), .ZN
       (n_127));
  DFFR_X1 \B_reg[0] (.RN (rstb), .CK (clk), .D (n_112), .Q (n_45), .QN
       (B[0]));
  XNOR2_X1 g5225__9682(.A (n_93), .B (n_99), .ZN (n_140));
  AOI21_X1 g5224__2683(.A (n_57), .B1 (n_113), .B2 (n_78), .ZN (n_124));
  NOR2_X1 g5267__1309(.A1 (n_126), .A2 (n_133), .ZN (n_123));
  XNOR2_X1 g5268__6877(.A (n_101), .B (n_82), .ZN (n_122));
  AOI21_X1 g5220__2900(.A (n_156), .B1 (n_97), .B2 (n_120), .ZN
       (n_121));
  NAND2_X1 g5212__2391(.A1 (n_119), .A2 (n_118), .ZN (n_150));
  XNOR2_X1 g5252__7675(.A (n_77), .B (n_54), .ZN (n_143));
  OR2_X1 g5211__7118(.A1 (n_119), .A2 (n_118), .ZN (n_151));
  DFFR_X1 \cycle_count_reg[2] (.RN (rstb), .CK (clk), .D (n_89), .Q
       (n_24), .QN (cycle_count[2]));
  NAND2_X1 g5231__1786(.A1 (n_98), .A2 (n_156), .ZN (n_116));
  AOI21_X1 g5249__5953(.A (n_133), .B1 (n_114), .B2 (n_91), .ZN
       (n_115));
  NAND2_X1 g5232__5703(.A1 (n_98), .A2 (B[4]), .ZN (n_128));
  XNOR2_X1 g5226__7114(.A (n_113), .B (n_79), .ZN (n_146));
  MUX2_X1 g5251__5266(.A (n_87), .B (n_50), .S (n_156), .Z (n_148));
  HA_X1 g5246__2250(.A (n_13), .B (n_59), .CO (n_111), .S (n_112));
  OR2_X1 g5266__6083(.A1 (n_109), .A2 (n_114), .ZN (n_110));
  INV_X1 g5236(.A (n_107), .ZN (n_108));
  NAND2_X1 g5288__2703(.A1 (n_80), .A2 (n_106), .ZN (n_134));
  XOR2_X1 g5238__5795(.A (cycle_count[3]), .B (n_74), .Z (n_105));
  XNOR2_X1 g5237__7344(.A (n_676), .B (n_30), .ZN (n_104));
  OAI22_X1 g5242__1840(.A1 (n_101), .A2 (n_81), .B1 (n_60), .B2
       (n_100), .ZN (n_142));
  NOR2_X1 g5279__5019(.A1 (n_94), .A2 (n_42), .ZN (n_99));
  INV_X1 g5245(.A (n_97), .ZN (n_98));
  INV_X1 g5276(.A (n_109), .ZN (n_96));
  SDFFR_X1 \A_reg[3] (.RN (rstb), .CK (clk), .D (n_95), .SE (n_100),
       .SI (A[3]), .Q (A[3]), .QN (UNCONNECTED14));
  SDFFR_X1 \A_reg[6] (.RN (rstb), .CK (clk), .D (B[6]), .SE (n_100),
       .SI (A[6]), .Q (A[6]), .QN (UNCONNECTED15));
  SDFFR_X1 \A_reg[8] (.RN (rstb), .CK (clk), .D (B[8]), .SE (n_100),
       .SI (A[8]), .Q (A[8]), .QN (UNCONNECTED16));
  AOI21_X1 g5221__1857(.A (n_94), .B1 (n_93), .B2 (n_41), .ZN (n_119));
  XNOR2_X1 g5227__9906(.A (n_65), .B (n_92), .ZN (n_157));
  OAI21_X1 g5228__8780(.A (n_68), .B1 (n_92), .B2 (n_69), .ZN (n_137));
  SDFFR_X1 \A_reg[11] (.RN (rstb), .CK (clk), .D (B[11]), .SE (n_100),
       .SI (A[11]), .Q (A[11]), .QN (UNCONNECTED17));
  INV_X1 g5277(.A (n_91), .ZN (n_126));
  NAND2_X1 g5230__4296(.A1 (n_88), .A2 (n_156), .ZN (n_90));
  AND2_X1 g5248__3772(.A1 (n_75), .A2 (n_100), .ZN (n_89));
  DFFR_X1 \cycle_count_reg[1] (.RN (rstb), .CK (clk), .D (n_73), .Q
       (n_25), .QN (cycle_count[1]));
  NAND2_X1 g5240__1474(.A1 (n_88), .A2 (B[5]), .ZN (n_107));
  OR2_X1 g5239__4547(.A1 (n_88), .A2 (B[5]), .ZN (n_136));
  SDFFR_X1 \A_reg[5] (.RN (rstb), .CK (clk), .D (B[5]), .SE (n_100),
       .SI (A[5]), .Q (A[5]), .QN (UNCONNECTED18));
  SDFFR_X1 \A_reg[0] (.RN (rstb), .CK (clk), .D (n_45), .SE (n_100),
       .SI (A[0]), .Q (A[0]), .QN (UNCONNECTED19));
  SDFFR_X1 \A_reg[9] (.RN (rstb), .CK (clk), .D (B[9]), .SE (n_100),
       .SI (A[9]), .Q (A[9]), .QN (UNCONNECTED20));
  SDFFR_X1 \A_reg[7] (.RN (rstb), .CK (clk), .D (B[7]), .SE (n_100),
       .SI (A[7]), .Q (A[7]), .QN (UNCONNECTED21));
  SDFFR_X1 \A_reg[4] (.RN (rstb), .CK (clk), .D (B[4]), .SE (n_100),
       .SI (A[4]), .Q (A[4]), .QN (UNCONNECTED22));
  SDFFR_X1 \A_reg[10] (.RN (rstb), .CK (clk), .D (B[10]), .SE (n_100),
       .SI (A[10]), .Q (A[10]), .QN (UNCONNECTED23));
  SDFFR_X1 \A_reg[2] (.RN (rstb), .CK (clk), .D (n_29), .SE (n_100),
       .SI (A[2]), .Q (A[2]), .QN (UNCONNECTED24));
  SDFFR_X1 \A_reg[1] (.RN (rstb), .CK (clk), .D (n_72), .SE (n_100),
       .SI (A[1]), .Q (A[1]), .QN (UNCONNECTED25));
  OAI21_X1 g5287__9682(.A (n_76), .B1 (n_55), .B2 (n_23), .ZN (n_87));
  NAND2_X1 g5284__2683(.A1 (n_84), .A2 (B[9]), .ZN (n_91));
  XNOR2_X1 g5275__1309(.A (n_83), .B (n_669), .ZN (n_113));
  NOR2_X1 g5281__6877(.A1 (n_84), .A2 (n_118), .ZN (n_109));
  AOI21_X4 g5271__2900(.A (n_34), .B1 (n_83), .B2 (n_38), .ZN (n_97));
  AND2_X1 g5282__2391(.A1 (n_84), .A2 (n_118), .ZN (n_114));
  INV_X1 g5301(.A (n_81), .ZN (n_82));
  INV_X1 g5300(.A (n_125), .ZN (n_80));
  NAND3_X1 g5290__7675(.A1 (n_56), .A2 (n_78), .A3 (n_100), .ZN (n_79));
  DFFR_X1 \OUT_reg[1] (.RN (rstb), .CK (clk), .D (n_675), .Q (OUT[1]),
       .QN (UNCONNECTED26));
  NAND2_X1 g5289__7118(.A1 (n_61), .A2 (n_76), .ZN (n_77));
  DFFR_X1 \cycle_count_reg[0] (.RN (rstb), .CK (clk), .D (n_62), .Q
       (n_26), .QN (cycle_count[0]));
  NAND3_X1 g5303__8757(.A1 (B[9]), .A2 (n_70), .A3 (n_100), .ZN
       (n_106));
  HA_X1 g5254__1786(.A (n_43), .B (n_24), .CO (n_74), .S (n_75));
  AND2_X1 g5302__5953(.A1 (n_44), .A2 (n_100), .ZN (n_73));
  XNOR2_X2 g5274__7114(.A (n_48), .B (n_63), .ZN (n_88));
  NAND2_X1 g5307__5266(.A1 (n_100), .A2 (n_72), .ZN (n_81));
  OAI21_X1 g5305__2250(.A (n_100), .B1 (n_71), .B2 (n_20), .ZN (n_94));
  NOR3_X1 g5306__6083(.A1 (B[9]), .A2 (n_70), .A3 (n_156), .ZN (n_125));
  NOR3_X1 g5308__2703(.A1 (B[9]), .A2 (n_0), .A3 (n_156), .ZN (n_133));
  NOR2_X1 g5278__5795(.A1 (n_67), .A2 (n_66), .ZN (n_69));
  NAND2_X1 g5286__7344(.A1 (n_67), .A2 (n_66), .ZN (n_68));
  XNOR2_X1 g5269__1840(.A (n_51), .B (n_66), .ZN (n_65));
  OAI22_X1 g5273__1857(.A1 (n_63), .A2 (n_36), .B1 (n_672), .B2 (n_35),
       .ZN (n_93));
  OR2_X1 g5295__9906(.A1 (n_156), .A2 (cycle_count[0]), .ZN (n_62));
  AOI21_X1 g5296__8780(.A (n_156), .B1 (n_60), .B2 (B[2]), .ZN (n_61));
  NOR2_X1 g5297__4296(.A1 (n_156), .A2 (B[0]), .ZN (n_59));
  NOR2_X1 g5304__3772(.A1 (n_18), .A2 (n_156), .ZN (n_58));
  NOR2_X1 g5298__1474(.A1 (B[8]), .A2 (n_156), .ZN (n_84));
  OR2_X1 g5299__4547(.A1 (B[7]), .A2 (n_156), .ZN (n_118));
  INV_X1 g5310(.A (n_56), .ZN (n_57));
  NAND2_X2 g5321__9682(.A1 (n_40), .A2 (n_22), .ZN (n_83));
  INV_X1 g5318(.A (n_54), .ZN (n_55));
  DFFR_X1 \OUT_reg[0] (.RN (rstb), .CK (clk), .D (n_46), .Q (OUT[0]),
       .QN (UNCONNECTED27));
  INV_X2 g5311(.A (n_156), .ZN (n_100));
  INV_X1 g5292(.A (n_51), .ZN (n_67));
  NAND2_X1 g5314__2683(.A1 (n_50), .A2 (n_95), .ZN (n_56));
  NOR2_X4 g5317__1309(.A1 (n_27), .A2 (cycle_count[3]), .ZN (n_156));
  XNOR2_X2 g5320__6877(.A (n_672), .B (n_7), .ZN (n_48));
  OR2_X1 g5315__2900(.A1 (n_50), .A2 (n_95), .ZN (n_78));
  XNOR2_X1 g5322__2391(.A (n_16), .B (n_1), .ZN (n_54));
  HA_X1 g5313__7675(.A (n_45), .B (A[0]), .CO (n_52), .S (n_46));
  HA_X1 g5312__7118(.A (n_26), .B (n_25), .CO (n_43), .S (n_44));
  INV_X1 g5323(.A (n_41), .ZN (n_42));
  NAND2_X1 g5324__8757(.A1 (n_15), .A2 (n_32), .ZN (n_40));
  XNOR2_X1 g5316__5953(.A (n_8), .B (n_31), .ZN (n_92));
  NAND2_X1 g5334__5703(.A1 (n_33), .A2 (n_37), .ZN (n_38));
  AND2_X1 g5326__7114(.A1 (n_35), .A2 (n_672), .ZN (n_36));
  NOR2_X1 g5325__5266(.A1 (n_33), .A2 (n_37), .ZN (n_34));
  NAND2_X1 g5339__2250(.A1 (n_32), .A2 (n_21), .ZN (n_51));
  AND2_X2 g5338__6083(.A1 (n_9), .A2 (n_31), .ZN (n_63));
  XNOR2_X1 g5327__2703(.A (A[2]), .B (n_29), .ZN (n_30));
  OR2_X1 g5328__7344(.A1 (n_60), .A2 (B[2]), .ZN (n_76));
  NOR2_X2 g5331__1840(.A1 (n_12), .A2 (n_31), .ZN (n_50));
  NOR3_X1 g5332__5019(.A1 (n_26), .A2 (n_25), .A3 (n_24), .ZN (n_27));
  AND2_X1 g5330__1857(.A1 (n_60), .A2 (B[2]), .ZN (n_23));
  NAND2_X1 g5333__9906(.A1 (n_21), .A2 (n_5), .ZN (n_22));
  NAND2_X1 g5329__8780(.A1 (n_71), .A2 (n_20), .ZN (n_41));
  XNOR2_X1 g5335__3772(.A (B[11]), .B (B[10]), .ZN (n_18));
  XNOR2_X1 g5336__1474(.A (B[11]), .B (A[11]), .ZN (n_17));
  INV_X1 g5340(.A (n_2), .ZN (n_16));
  INV_X1 g5342(.A (n_21), .ZN (n_15));
  INV_X1 g5341(.A (n_12), .ZN (n_13));
  INV_X1 g5354(.A (n_8), .ZN (n_9));
  INV_X1 g5343(.A (n_7), .ZN (n_35));
  INV_X1 g5357(.A (n_6), .ZN (n_33));
  INV_X1 g5355(.A (n_5), .ZN (n_32));
  NAND2_X1 g5360__6877(.A1 (IN[3]), .A2 (W[1]), .ZN (n_8));
  NAND2_X1 g5348__2900(.A1 (W[1]), .A2 (n_279), .ZN (n_101));
  NAND2_X1 g5353__2391(.A1 (IN[3]), .A2 (W[2]), .ZN (n_7));
  NAND2_X1 g5352__7675(.A1 (IN[1]), .A2 (n_274), .ZN (n_66));
  NAND2_X1 g5350__7118(.A1 (IN[2]), .A2 (W[2]), .ZN (n_31));
  NAND2_X2 g5367__8757(.A1 (IN[1]), .A2 (W[2]), .ZN (n_37));
  NAND2_X1 g5363__1786(.A1 (n_320), .A2 (n_274), .ZN (n_71));
  AND2_X1 g5358__5953(.A1 (IN[1]), .A2 (W[0]), .ZN (n_3));
  NAND2_X1 g5346__5703(.A1 (IN[0]), .A2 (W[2]), .ZN (n_2));
  NAND2_X1 g5361__7114(.A1 (W[0]), .A2 (IN[2]), .ZN (n_1));
  NAND2_X2 g5366__5266(.A1 (IN[0]), .A2 (W[3]), .ZN (n_6));
  NAND2_X1 g5364__2250(.A1 (IN[2]), .A2 (W[1]), .ZN (n_5));
  NAND2_X1 g5349__6083(.A1 (W[0]), .A2 (IN[0]), .ZN (n_12));
  NAND2_X1 g5351__2703(.A1 (W[0]), .A2 (IN[3]), .ZN (n_21));
  NAND2_X1 g5347__5795(.A1 (IN[1]), .A2 (W[1]), .ZN (n_60));
  FA_X1 g2(.A (A[2]), .B (n_29), .CI (n_676), .CO (n_234), .S
       (UNCONNECTED28));
  BUF_X1 drc_buf_sp5453(.A (IN[0]), .Z (n_279));
  CLKBUF_X1 drc_buf_sp5485(.A (IN[3]), .Z (n_320));
  INV_X1 fopt(.A (n_397), .ZN (n_274));
  INV_X1 fopt5545(.A (W[3]), .ZN (n_397));
  XOR2_X1 g5756(.A (n_37), .B (n_6), .Z (n_669));
  AND2_X2 g5759(.A1 (IN[2]), .A2 (W[3]), .ZN (n_672));
  OR2_X1 g5760(.A1 (n_140), .A2 (n_163), .ZN (n_673));
  OAI21_X1 g5761(.A (n_214), .B1 (n_212), .B2 (n_135), .ZN (n_674));
  FA_X1 g5762(.A (n_72), .B (A[1]), .CI (n_52), .CO (n_676), .S
       (n_675));
  XOR2_X1 g5843(.A (n_146), .B (n_148), .Z (n_781));
endmodule

