
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Jun  6 2024 17:50:03 CDT (Jun  6 2024 22:50:03 UTC)

// Verification Directory fv/mac 

module mac(IN, W, clk, rstb, OUT);
  input [3:0] IN, W;
  input clk, rstb;
  output [11:0] OUT;
  wire [3:0] IN, W;
  wire clk, rstb;
  wire [11:0] OUT;
  wire [11:0] B;
  wire [11:0] A;
  wire [3:0] cycle_count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_8, n_10, n_11, n_12;
  wire n_14, n_15, n_16, n_18, n_19, n_20, n_21, n_23;
  wire n_24, n_25, n_26, n_27, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_233, n_235, n_310, n_459, n_624;
  wire n_625, n_626, n_627;
  DFFR_X1 \OUT_reg[11] (.RN (rstb), .CK (clk), .D (n_222), .Q
       (OUT[11]), .QN (UNCONNECTED));
  XNOR2_X1 g5136__8780(.A (n_220), .B (n_18), .ZN (n_222));
  DFFR_X1 \OUT_reg[10] (.RN (rstb), .CK (clk), .D (n_221), .Q
       (OUT[10]), .QN (UNCONNECTED0));
  FA_X1 g5141__4296(.A (B[10]), .B (A[10]), .CI (n_218), .CO (n_220),
       .S (n_221));
  DFFR_X1 \OUT_reg[9] (.RN (rstb), .CK (clk), .D (n_219), .Q (OUT[9]),
       .QN (UNCONNECTED1));
  FA_X1 g5150__3772(.A (B[9]), .B (A[9]), .CI (n_216), .CO (n_218), .S
       (n_219));
  DFFR_X1 \B_reg[10] (.RN (rstb), .CK (clk), .D (n_215), .Q (B[10]),
       .QN (n_70));
  DFFR_X1 \OUT_reg[8] (.RN (rstb), .CK (clk), .D (n_217), .Q (OUT[8]),
       .QN (UNCONNECTED2));
  FA_X1 g5156__1474(.A (B[8]), .B (A[8]), .CI (n_204), .CO (n_216), .S
       (n_217));
  NAND2_X1 g5132__4547(.A1 (n_213), .A2 (n_212), .ZN (n_215));
  DFFR_X1 \B_reg[11] (.RN (rstb), .CK (clk), .D (n_214), .Q (B[11]),
       .QN (UNCONNECTED3));
  XNOR2_X1 g5139__9682(.A (n_206), .B (n_60), .ZN (n_214));
  OAI21_X1 g5135__2683(.A (n_210), .B1 (n_211), .B2 (n_209), .ZN
       (n_213));
  DFFR_X1 \B_reg[9] (.RN (rstb), .CK (clk), .D (n_208), .Q (B[9]), .QN
       (UNCONNECTED4));
  OR3_X1 g5138__1309(.A1 (n_211), .A2 (n_210), .A3 (n_209), .ZN
       (n_212));
  XNOR2_X1 g5140__6877(.A (n_207), .B (n_126), .ZN (n_208));
  DFFR_X1 \OUT_reg[7] (.RN (rstb), .CK (clk), .D (n_205), .Q (OUT[7]),
       .QN (UNCONNECTED5));
  NOR2_X1 g5143__2900(.A1 (n_207), .A2 (n_128), .ZN (n_211));
  OAI211_X1 g5146__2391(.A (n_201), .B (n_109), .C1 (n_122), .C2
       (n_127), .ZN (n_206));
  DFFR_X1 \B_reg[8] (.RN (rstb), .CK (clk), .D (n_203), .Q (B[8]), .QN
       (n_1));
  FA_X1 g5161__7675(.A (B[7]), .B (A[7]), .CI (n_198), .CO (n_204), .S
       (n_205));
  AOI21_X2 g5144__7118(.A (n_121), .B1 (n_202), .B2 (n_100), .ZN
       (n_207));
  XNOR2_X1 g5145__8757(.A (n_202), .B (n_113), .ZN (n_203));
  NAND2_X1 g5149__1786(.A1 (n_202), .A2 (n_129), .ZN (n_201));
  DFFR_X1 \B_reg[7] (.RN (rstb), .CK (clk), .D (n_200), .Q (B[7]), .QN
       (UNCONNECTED6));
  OAI21_X1 g5151__5953(.A (n_150), .B1 (n_197), .B2 (n_133), .ZN
       (n_202));
  DFFR_X1 \OUT_reg[6] (.RN (rstb), .CK (clk), .D (n_199), .Q (OUT[6]),
       .QN (UNCONNECTED7));
  XNOR2_X1 g5152__5703(.A (n_196), .B (n_151), .ZN (n_200));
  FA_X1 g5166__7114(.A (B[6]), .B (A[6]), .CI (n_190), .CO (n_198), .S
       (n_199));
  DFFR_X1 \B_reg[6] (.RN (rstb), .CK (clk), .D (n_195), .Q (B[6]), .QN
       (n_21));
  INV_X1 g5155(.A (n_196), .ZN (n_197));
  OAI21_X2 g5157__5266(.A (n_624), .B1 (n_194), .B2 (n_181), .ZN
       (n_196));
  XNOR2_X1 g5158__2250(.A (n_182), .B (n_194), .ZN (n_195));
  DFFR_X1 \B_reg[5] (.RN (rstb), .CK (clk), .D (n_193), .Q (B[5]), .QN
       (n_0));
  DFFR_X1 \OUT_reg[5] (.RN (rstb), .CK (clk), .D (n_191), .Q (OUT[5]),
       .QN (UNCONNECTED8));
  AOI21_X4 g5162__6083(.A (n_171), .B1 (n_192), .B2 (n_179), .ZN
       (n_194));
  XNOR2_X1 g5163__2703(.A (n_180), .B (n_192), .ZN (n_193));
  FA_X1 g5172__5795(.A (B[5]), .B (A[5]), .CI (n_185), .CO (n_190), .S
       (n_191));
  DFFR_X1 \B_reg[4] (.RN (rstb), .CK (clk), .D (n_189), .Q (B[4]), .QN
       (n_91));
  NAND2_X2 g5167__7344(.A1 (n_188), .A2 (n_174), .ZN (n_192));
  XOR2_X1 g5168__1840(.A (n_173), .B (n_187), .Z (n_189));
  NAND2_X1 g5171__5019(.A1 (n_169), .A2 (n_187), .ZN (n_188));
  DFFR_X1 \B_reg[3] (.RN (rstb), .CK (clk), .D (n_184), .Q (n_97), .QN
       (B[3]));
  DFFR_X1 \OUT_reg[4] (.RN (rstb), .CK (clk), .D (n_186), .Q (OUT[4]),
       .QN (UNCONNECTED9));
  FA_X1 g5181__1857(.A (B[4]), .B (A[4]), .CI (n_167), .CO (n_185), .S
       (n_186));
  OAI21_X2 g5173__9906(.A (n_142), .B1 (n_140), .B2 (n_183), .ZN
       (n_187));
  XNOR2_X1 g5174__8780(.A (n_625), .B (n_183), .ZN (n_184));
  NOR2_X1 g5177__4296(.A1 (n_181), .A2 (n_176), .ZN (n_182));
  DFFR_X1 \B_reg[2] (.RN (rstb), .CK (clk), .D (n_178), .Q (n_33), .QN
       (B[2]));
  NAND2_X1 g5178__3772(.A1 (n_179), .A2 (n_170), .ZN (n_180));
  XOR2_X1 g5192__1474(.A (n_156), .B (n_177), .Z (n_178));
  AOI21_X2 g5190__4547(.A (n_155), .B1 (n_145), .B2 (n_177), .ZN
       (n_183));
  INV_X1 g5180(.A (n_624), .ZN (n_176));
  INV_X1 g5179(.A (n_172), .ZN (n_174));
  HA_X1 g5182__9682(.A (n_157), .B (n_152), .CO (n_172), .S (n_173));
  INV_X1 g5185(.A (n_170), .ZN (n_171));
  DFFR_X1 \OUT_reg[3] (.RN (rstb), .CK (clk), .D (n_168), .Q (OUT[3]),
       .QN (UNCONNECTED10));
  DFFR_X1 \B_reg[1] (.RN (rstb), .CK (clk), .D (n_166), .Q (n_71), .QN
       (B[1]));
  NAND2_X1 g5187__1309(.A1 (n_165), .A2 (n_160), .ZN (n_179));
  AND2_X1 g5184__6877(.A1 (n_162), .A2 (n_137), .ZN (n_181));
  NAND2_X1 g5195__2900(.A1 (n_158), .A2 (n_153), .ZN (n_169));
  NAND2_X1 g5186__2391(.A1 (n_159), .A2 (n_164), .ZN (n_170));
  FA_X1 g5197__7675(.A (n_97), .B (A[3]), .CI (n_233), .CO (n_167), .S
       (n_168));
  FA_X1 g5198__7118(.A (n_116), .B (n_5), .CI (n_125), .CO (n_177), .S
       (n_166));
  INV_X1 g5188(.A (n_164), .ZN (n_165));
  OAI21_X1 g5189__8757(.A (n_101), .B1 (n_149), .B2 (n_161), .ZN
       (n_164));
  MUX2_X1 g5193__1786(.A (n_147), .B (n_72), .S (n_161), .Z (n_162));
  INV_X1 g5201(.A (n_159), .ZN (n_160));
  INV_X1 g5202(.A (n_157), .ZN (n_158));
  HA_X1 g5205__5953(.A (n_144), .B (n_143), .CO (n_155), .S (n_156));
  XNOR2_X1 g5203__5703(.A (n_135), .B (n_146), .ZN (n_159));
  XNOR2_X2 g5204__5266(.A (n_136), .B (n_148), .ZN (n_157));
  INV_X1 g5207(.A (n_152), .ZN (n_153));
  DFFR_X1 \cycle_count_reg[3] (.RN (rstb), .CK (clk), .D (n_131), .Q
       (UNCONNECTED11), .QN (cycle_count[3]));
  NAND2_X1 g5206__2250(.A1 (n_132), .A2 (n_150), .ZN (n_151));
  AOI21_X1 g5200__6083(.A (n_120), .B1 (n_148), .B2 (n_93), .ZN
       (n_149));
  AOI21_X1 g5199__2703(.A (n_108), .B1 (n_134), .B2 (n_146), .ZN
       (n_147));
  OAI21_X2 g5209__5795(.A (n_114), .B1 (n_111), .B2 (n_161), .ZN
       (n_152));
  OR2_X2 g5220__7344(.A1 (n_144), .A2 (n_143), .ZN (n_145));
  NAND2_X1 g5217__1840(.A1 (n_139), .A2 (n_141), .ZN (n_142));
  NOR2_X1 g5216__5019(.A1 (n_139), .A2 (n_141), .ZN (n_140));
  NAND2_X1 g5218__1857(.A1 (n_115), .A2 (n_119), .ZN (n_136));
  NAND3_X1 g5215__9906(.A1 (n_134), .A2 (n_107), .A3 (n_102), .ZN
       (n_135));
  INV_X1 g5210(.A (n_132), .ZN (n_133));
  NOR2_X1 g5219__8780(.A1 (n_105), .A2 (n_161), .ZN (n_131));
  DFFR_X1 \OUT_reg[2] (.RN (rstb), .CK (clk), .D (n_106), .Q (OUT[2]),
       .QN (UNCONNECTED12));
  NOR3_X1 g5250__4296(.A1 (n_112), .A2 (n_128), .A3 (n_127), .ZN
       (n_129));
  DFFR_X1 \B_reg[0] (.RN (rstb), .CK (clk), .D (n_117), .Q (n_47), .QN
       (B[0]));
  XNOR2_X1 g5226__3772(.A (n_95), .B (n_99), .ZN (n_137));
  NOR2_X1 g5267__1474(.A1 (n_128), .A2 (n_209), .ZN (n_126));
  XNOR2_X1 g5265__4547(.A (n_103), .B (n_79), .ZN (n_125));
  OR2_X1 g5212__9682(.A1 (n_124), .A2 (n_123), .ZN (n_150));
  NAND2_X1 g5213__2683(.A1 (n_124), .A2 (n_123), .ZN (n_132));
  XNOR2_X2 g5252__1309(.A (n_56), .B (n_84), .ZN (n_144));
  DFFR_X1 \cycle_count_reg[2] (.RN (rstb), .CK (clk), .D (n_90), .Q
       (n_23), .QN (cycle_count[2]));
  AOI21_X1 g5249__6877(.A (n_209), .B1 (n_121), .B2 (n_94), .ZN
       (n_122));
  INV_X1 g5230(.A (n_119), .ZN (n_120));
  MUX2_X2 g5251__2391(.A (n_83), .B (n_54), .S (n_161), .Z (n_141));
  XNOR2_X2 g5227__7675(.A (n_110), .B (n_88), .ZN (n_139));
  HA_X1 g5246__7118(.A (n_16), .B (n_62), .CO (n_116), .S (n_117));
  AOI21_X1 g5221__8757(.A (n_161), .B1 (n_92), .B2 (n_91), .ZN (n_115));
  NAND2_X1 g5232__1786(.A1 (n_104), .A2 (n_161), .ZN (n_114));
  OR2_X1 g5266__5953(.A1 (n_112), .A2 (n_121), .ZN (n_113));
  AOI21_X1 g5225__5703(.A (n_59), .B1 (n_110), .B2 (n_87), .ZN (n_111));
  NAND2_X1 g5287__7114(.A1 (n_80), .A2 (n_109), .ZN (n_210));
  INV_X1 g5237(.A (n_107), .ZN (n_108));
  XNOR2_X1 g5238__5266(.A (n_627), .B (n_30), .ZN (n_106));
  XOR2_X1 g5239__2250(.A (cycle_count[3]), .B (n_75), .Z (n_105));
  NAND2_X1 g5233__6083(.A1 (n_104), .A2 (B[4]), .ZN (n_119));
  NAND2_X1 g5240__2703(.A1 (n_77), .A2 (n_0), .ZN (n_134));
  OAI22_X1 g5243__5795(.A1 (n_103), .A2 (n_78), .B1 (n_29), .B2
       (n_102), .ZN (n_143));
  NAND2_X1 g5231__7344(.A1 (n_89), .A2 (n_161), .ZN (n_101));
  INV_X1 g5275(.A (n_112), .ZN (n_100));
  NOR2_X1 g5278__1840(.A1 (n_96), .A2 (n_41), .ZN (n_99));
  SDFFR_X1 \A_reg[11] (.RN (rstb), .CK (clk), .D (B[11]), .SE (n_102),
       .SI (A[11]), .Q (A[11]), .QN (UNCONNECTED13));
  XNOR2_X1 g5228__5019(.A (n_65), .B (n_98), .ZN (n_148));
  OAI21_X1 g5229__1857(.A (n_68), .B1 (n_98), .B2 (n_69), .ZN (n_146));
  SDFFR_X1 \A_reg[3] (.RN (rstb), .CK (clk), .D (n_97), .SE (n_102),
       .SI (A[3]), .Q (A[3]), .QN (UNCONNECTED14));
  AOI21_X1 g5222__9906(.A (n_96), .B1 (n_95), .B2 (n_40), .ZN (n_124));
  INV_X1 g5276(.A (n_94), .ZN (n_128));
  SDFFR_X1 \A_reg[2] (.RN (rstb), .CK (clk), .D (n_33), .SE (n_102),
       .SI (A[2]), .Q (A[2]), .QN (UNCONNECTED15));
  SDFFR_X1 \A_reg[1] (.RN (rstb), .CK (clk), .D (n_71), .SE (n_102),
       .SI (A[1]), .Q (A[1]), .QN (UNCONNECTED16));
  NAND2_X1 g5234__8780(.A1 (n_92), .A2 (n_91), .ZN (n_93));
  AND2_X1 g5248__4296(.A1 (n_76), .A2 (n_102), .ZN (n_90));
  DFFR_X1 \cycle_count_reg[1] (.RN (rstb), .CK (clk), .D (n_73), .Q
       (n_24), .QN (cycle_count[1]));
  SDFFR_X1 \A_reg[10] (.RN (rstb), .CK (clk), .D (B[10]), .SE (n_102),
       .SI (A[10]), .Q (A[10]), .QN (UNCONNECTED17));
  SDFFR_X1 \A_reg[5] (.RN (rstb), .CK (clk), .D (B[5]), .SE (n_102),
       .SI (A[5]), .Q (A[5]), .QN (UNCONNECTED18));
  SDFFR_X1 \A_reg[6] (.RN (rstb), .CK (clk), .D (B[6]), .SE (n_102),
       .SI (A[6]), .Q (A[6]), .QN (UNCONNECTED19));
  SDFFR_X1 \A_reg[7] (.RN (rstb), .CK (clk), .D (B[7]), .SE (n_102),
       .SI (A[7]), .Q (A[7]), .QN (UNCONNECTED20));
  SDFFR_X1 \A_reg[8] (.RN (rstb), .CK (clk), .D (B[8]), .SE (n_102),
       .SI (A[8]), .Q (A[8]), .QN (UNCONNECTED21));
  SDFFR_X1 \A_reg[9] (.RN (rstb), .CK (clk), .D (B[9]), .SE (n_102),
       .SI (A[9]), .Q (A[9]), .QN (UNCONNECTED22));
  SDFFR_X1 \A_reg[0] (.RN (rstb), .CK (clk), .D (n_47), .SE (n_102),
       .SI (A[0]), .Q (A[0]), .QN (UNCONNECTED23));
  SDFFR_X1 \A_reg[4] (.RN (rstb), .CK (clk), .D (B[4]), .SE (n_102),
       .SI (A[4]), .Q (A[4]), .QN (UNCONNECTED24));
  NAND2_X1 g5241__3772(.A1 (n_89), .A2 (B[5]), .ZN (n_107));
  NAND3_X1 g5289__1474(.A1 (n_58), .A2 (n_87), .A3 (n_102), .ZN (n_88));
  NAND3_X2 g5288__4547(.A1 (n_82), .A2 (n_42), .A3 (n_102), .ZN (n_84));
  OAI21_X1 g5286__9682(.A (n_82), .B1 (n_57), .B2 (n_43), .ZN (n_83));
  NAND2_X1 g5283__2683(.A1 (n_81), .A2 (B[9]), .ZN (n_94));
  NOR2_X1 g5280__1309(.A1 (n_81), .A2 (n_123), .ZN (n_112));
  AND2_X1 g5281__6877(.A1 (n_81), .A2 (n_123), .ZN (n_121));
  DFFR_X1 \OUT_reg[1] (.RN (rstb), .CK (clk), .D (n_626), .Q (OUT[1]),
       .QN (UNCONNECTED25));
  INV_X1 g5300(.A (n_127), .ZN (n_80));
  INV_X1 g5299(.A (n_78), .ZN (n_79));
  INV_X1 g5245(.A (n_89), .ZN (n_77));
  DFFR_X1 \cycle_count_reg[0] (.RN (rstb), .CK (clk), .D (n_61), .Q
       (n_25), .QN (cycle_count[0]));
  INV_X2 g5244(.A (n_92), .ZN (n_104));
  NAND3_X1 g5303__2900(.A1 (B[9]), .A2 (n_70), .A3 (n_102), .ZN
       (n_109));
  HA_X1 g5254__2391(.A (n_45), .B (n_23), .CO (n_75), .S (n_76));
  XNOR2_X2 g5274__7675(.A (n_51), .B (n_235), .ZN (n_110));
  AOI21_X4 g5270__8757(.A (n_39), .B1 (n_235), .B2 (n_37), .ZN (n_92));
  XNOR2_X2 g5273__1786(.A (n_50), .B (n_63), .ZN (n_89));
  AND2_X1 g5294__5953(.A1 (n_46), .A2 (n_102), .ZN (n_73));
  OAI21_X1 g5302__5703(.A (n_102), .B1 (n_72), .B2 (n_21), .ZN (n_96));
  NAND2_X1 g5304__7114(.A1 (n_102), .A2 (n_71), .ZN (n_78));
  NOR3_X1 g5305__5266(.A1 (B[9]), .A2 (n_70), .A3 (n_161), .ZN (n_127));
  NOR3_X1 g5306__2250(.A1 (B[9]), .A2 (n_1), .A3 (n_161), .ZN (n_209));
  NOR2_X1 g5277__6083(.A1 (n_67), .A2 (n_66), .ZN (n_69));
  NAND2_X1 g5285__2703(.A1 (n_67), .A2 (n_66), .ZN (n_68));
  XNOR2_X1 g5268__5795(.A (n_55), .B (n_66), .ZN (n_65));
  OAI22_X1 g5269__1840(.A1 (n_63), .A2 (n_35), .B1 (n_49), .B2 (n_34),
       .ZN (n_95));
  NOR2_X1 g5296__5019(.A1 (n_161), .A2 (B[0]), .ZN (n_62));
  OR2_X1 g5295__1857(.A1 (n_161), .A2 (cycle_count[0]), .ZN (n_61));
  NOR2_X1 g5301__9906(.A1 (n_11), .A2 (n_161), .ZN (n_60));
  NOR2_X1 g5297__8780(.A1 (B[8]), .A2 (n_161), .ZN (n_81));
  OR2_X1 g5298__4296(.A1 (B[7]), .A2 (n_161), .ZN (n_123));
  INV_X1 g5308(.A (n_58), .ZN (n_59));
  INV_X2 g5309(.A (n_161), .ZN (n_102));
  INV_X1 g5316(.A (n_56), .ZN (n_57));
  DFFR_X1 \OUT_reg[0] (.RN (rstb), .CK (clk), .D (n_48), .Q (OUT[0]),
       .QN (UNCONNECTED26));
  INV_X1 g5291(.A (n_55), .ZN (n_67));
  XNOR2_X2 g5320__1474(.A (n_14), .B (n_4), .ZN (n_56));
  NAND2_X1 g5312__4547(.A1 (n_54), .A2 (n_97), .ZN (n_58));
  INV_X1 g5292(.A (n_44), .ZN (n_51));
  XNOR2_X2 g5318__9682(.A (n_49), .B (n_12), .ZN (n_50));
  OR2_X1 g5313__2683(.A1 (n_54), .A2 (n_97), .ZN (n_87));
  NOR2_X4 g5315__1309(.A1 (n_26), .A2 (cycle_count[3]), .ZN (n_161));
  HA_X1 g5311__6877(.A (n_47), .B (A[0]), .CO (n_52), .S (n_48));
  HA_X1 g5310__2900(.A (n_25), .B (n_24), .CO (n_45), .S (n_46));
  XNOR2_X1 g5317__2391(.A (n_38), .B (n_6), .ZN (n_44));
  INV_X1 g5321(.A (n_42), .ZN (n_43));
  INV_X1 g5322(.A (n_40), .ZN (n_41));
  NOR2_X2 g5323__7675(.A1 (n_36), .A2 (n_38), .ZN (n_39));
  XNOR2_X1 g5314__7118(.A (n_31), .B (n_19), .ZN (n_98));
  NAND2_X1 g5332__8757(.A1 (n_36), .A2 (n_38), .ZN (n_37));
  AND2_X1 g5324__1786(.A1 (n_34), .A2 (n_49), .ZN (n_35));
  NAND2_X1 g5327__5953(.A1 (n_10), .A2 (n_33), .ZN (n_82));
  NAND2_X1 g5337__5703(.A1 (n_8), .A2 (n_32), .ZN (n_55));
  AND2_X2 g5336__7114(.A1 (n_20), .A2 (n_31), .ZN (n_63));
  XNOR2_X1 g5325__5266(.A (A[2]), .B (n_33), .ZN (n_30));
  NAND2_X1 g5326__2250(.A1 (n_29), .A2 (B[2]), .ZN (n_42));
  NOR2_X2 g5329__6083(.A1 (n_15), .A2 (n_31), .ZN (n_54));
  NOR3_X1 g5330__5795(.A1 (n_25), .A2 (n_24), .A3 (n_23), .ZN (n_26));
  NAND2_X1 g5328__1840(.A1 (n_72), .A2 (n_21), .ZN (n_40));
  INV_X1 g5352(.A (n_19), .ZN (n_20));
  XNOR2_X1 g5334__5019(.A (B[11]), .B (A[11]), .ZN (n_18));
  INV_X1 g5340(.A (n_15), .ZN (n_16));
  INV_X1 g5338(.A (n_2), .ZN (n_14));
  INV_X1 g5341(.A (n_12), .ZN (n_34));
  XNOR2_X1 g5333__8780(.A (B[11]), .B (B[10]), .ZN (n_11));
  INV_X1 g5339(.A (n_29), .ZN (n_10));
  INV_X1 g5353(.A (n_27), .ZN (n_8));
  INV_X1 g5355(.A (n_6), .ZN (n_36));
  INV_X2 g5354(.A (n_3), .ZN (n_49));
  AND2_X1 g5356__1474(.A1 (IN[1]), .A2 (W[0]), .ZN (n_5));
  NAND2_X1 g5359__4547(.A1 (W[0]), .A2 (IN[2]), .ZN (n_4));
  NAND2_X2 g5363__9682(.A1 (IN[2]), .A2 (W[3]), .ZN (n_3));
  NAND2_X1 g5346__2683(.A1 (IN[0]), .A2 (W[1]), .ZN (n_103));
  NAND2_X1 g5351__1309(.A1 (IN[3]), .A2 (W[2]), .ZN (n_12));
  NAND2_X2 g5347__6877(.A1 (IN[0]), .A2 (W[0]), .ZN (n_15));
  NAND2_X2 g5345__2900(.A1 (IN[1]), .A2 (W[1]), .ZN (n_29));
  NAND2_X1 g5361__2391(.A1 (n_459), .A2 (n_310), .ZN (n_72));
  NAND2_X1 g5344__7675(.A1 (IN[0]), .A2 (W[2]), .ZN (n_2));
  NAND2_X1 g5364__7118(.A1 (IN[0]), .A2 (W[3]), .ZN (n_6));
  NAND2_X1 g5358__8757(.A1 (IN[3]), .A2 (W[1]), .ZN (n_19));
  NAND2_X2 g5365__1786(.A1 (IN[1]), .A2 (W[2]), .ZN (n_38));
  NAND2_X1 g5350__5953(.A1 (IN[1]), .A2 (W[3]), .ZN (n_66));
  NAND2_X2 g5349__5703(.A1 (IN[3]), .A2 (W[0]), .ZN (n_32));
  NAND2_X4 g5362__7114(.A1 (IN[2]), .A2 (W[1]), .ZN (n_27));
  NAND2_X2 g5348__5266(.A1 (IN[2]), .A2 (W[2]), .ZN (n_31));
  FA_X1 g2(.A (A[2]), .B (n_33), .CI (n_627), .CO (n_233), .S
       (UNCONNECTED27));
  XNOR2_X2 g5419(.A (n_32), .B (n_27), .ZN (n_235));
  CLKBUF_X1 drc_buf_sp5477(.A (W[3]), .Z (n_310));
  CLKBUF_X1 drc_buf_sp5593(.A (IN[3]), .Z (n_459));
  OR2_X1 g5722(.A1 (n_162), .A2 (n_137), .ZN (n_624));
  XOR2_X1 g5723(.A (n_139), .B (n_141), .Z (n_625));
  FA_X1 g5724(.A (n_71), .B (A[1]), .CI (n_52), .CO (n_627), .S
       (n_626));
endmodule

